# Generated by Django 2.2.5 on 2019-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cards",
            fields=[
                ("card_id", models.TextField(primary_key=True, serialize=False)),
                ("dbf_id", models.TextField()),
                ("name", models.TextField(help_text="Card's Name")),
                ("card_set", models.TextField(help_text="Card's Expansion Set")),
                ("type", models.TextField(help_text="Card's Type")),
                (
                    "player_class",
                    models.TextField(
                        choices=[
                            ("Druid", "Druid"),
                            ("Hunter", "Hunter"),
                            ("Mage", "Mage"),
                            ("Paladin", "Paladin"),
                            ("Priest", "Priest"),
                            ("Rogue", "Rogue"),
                            ("Shaman", "Shaman"),
                            ("Warlock", "Warlock"),
                            ("Warrior", "Warrior"),
                            ("Neutral", "Neutral"),
                        ]
                    ),
                ),
                (
                    "collectible",
                    models.BooleanField(
                        help_text="Whether the card is collectible. Collectible means able to build a standard deck with this card"
                    ),
                ),
            ],
        )
    ]
